name: CD - GCP IAM RBAC Org (Destroy)

on:
  workflow_dispatch:
    inputs:

      project_id:
        description: GCP project ID
        required: true
        type: string

      region:
        description: "GCP region (Free Tier: us-west1, us-central1, us-east1)"
        required: true
        type: string
        default: us-central1

      team_permissions:
        description: team permissions
        required: true
        type: string

      devops_members:
        description: devops members
        required: true
        type: string

      developer_members:
        description: developer members
        required: true
        type: string

      devops_group_name:
        description: devops group name
        required: true
        type: string

      developer_group_name:
        description: developer group name
        required: true
        type: string

env:
  TF_BUCKET_NAME: ${{ secrets.TF_BUCKET_NAME }}
  TF_BUCKET_PREFIX: ${{ secrets.TF_BUCKET_PREFIX }}
jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=$TF_BUCKET_NAME" \
          -backend-config="prefix=$TF_BUCKET_PREFIX"
    - name: Terraform Plan
      run: |
        terraform plan -destroy  \
          -var="project_id=${{ github.event.inputs.project_id }}" \
          -var="region=${{ github.event.inputs.region }}" \
          -var="team_permissions=${{ github.event.inputs.team_permissions }}" \
          -var="devops_members=${{ github.event.inputs.devops_members }}" \
          -var="developer_members=${{ github.event.inputs.developer_members }}" \
          -var="devops_group_name=${{ github.event.inputs.devops_group_name }}" \
          -var="developer_group_name=${{ github.event.inputs.developer_group_name }}"
    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve  \
          -var="project_id=${{ github.event.inputs.project_id }}" \
          -var="region=${{ github.event.inputs.region }}" \
          -var="team_permissions=${{ github.event.inputs.team_permissions }}" \
          -var="devops_members=${{ github.event.inputs.devops_members }}" \
          -var="developer_members=${{ github.event.inputs.developer_members }}" \
          -var="devops_group_name=${{ github.event.inputs.devops_group_name }}" \
          -var="developer_group_name=${{ github.event.inputs.developer_group_name }}"
